---
title: "linear_SVM"
format: html
editor: visual
---

## packages

```{r}

library(caret)
library(e1071)
library(dplyr)

rna <- read.csv("tcga_rna_count_data_crc.csv", row.names = 1)
prediction <- read.csv("prediction_file_crc.csv")
```

```{r}
# Preprocessing - transpose, fix sample IDs, align samples
rna_t <- t(rna)

rna_t <- as.data.frame(rna_t)

#dim(rna_t)

prediction$X <- gsub("-", ".", prediction$X)

rownames(prediction) <- prediction$X
prediction$X <- NULL

common_samples <- intersect(rownames(rna_t), rownames(prediction))

#length(common_samples)  # should be 462 (or very close)

rna_t <- rna_t[common_samples, ]
prediction <- prediction[common_samples, ]
```


```{r}
nzv <- nearZeroVar(rna_t)

#length(nzv)  # how many genes removed?

rna_t_filtered <- rna_t[, -nzv]

#dim(rna_t_filtered)
```

```{r}
# Keep only rows that are NOT 'Indeterminate'
prediction <- subset(prediction, msi_status != "X" & msi_status != "Indeterminate")

prediction$msi_status <- as.factor(prediction$msi_status)

prediction$msi_status <- droplevels(prediction$msi_status)

levels(prediction$msi_status) <- make.names(levels(prediction$msi_status))

table(prediction$msi_status)

# Optional: set reference levels (important for recall)
#prediction$msi_status <- factor(prediction$msi_status, levels = c("MSI-H", "MSI-L", "MSS"))
```
```{r}
common_samples <- intersect(rownames(rna_t), rownames(prediction))

rna_t_filtered <- rna_t[common_samples, ]
prediction <- prediction[common_samples, ]
```

```{r}
set.seed(123)

trainIndex <- createDataPartition(prediction$KRAS, 
                                   p = 0.8, 
                                   list = FALSE)

x_train <- rna_t_filtered[trainIndex, ]
x_test  <- rna_t_filtered[-trainIndex, ]

y_train <- prediction$msi_status[trainIndex]
y_test  <- prediction$msi_status[-trainIndex]
```

```{r}
preProc <- preProcess(x_train, method = c("center", "scale"))

x_train_scaled <- predict(preProc, x_train)
x_test_scaled  <- predict(preProc, x_test)
```

```{r}
ctrl <- trainControl(method = "cv",
                     number = 5,
                     classProbs = TRUE,
                     summaryFunction = multiClassSummary)

svm_model <- train(x = x_train_scaled,
                   y = y_train,
                   method = "svmLinear",
                   trControl = ctrl,
                   metric = "Accuracy")
```

```{r}
predictions <- predict(svm_model, x_test_scaled)
cm <- confusionMatrix(predictions, y_test)
cm

library(pROC)

prob <- predict(svm_model, x_test_scaled, type = "prob")
roc_obj <- roc(y_test, prob[,2])

auc(roc_obj)
plot(roc_obj)
```

```{r}
weights <- svm_model$finalModel@W  # note the @ symbol

gene_names <- colnames(x_train_scaled)

coef_df <- data.frame(
  Gene = gene_names,
  Weight = as.numeric(weights)
)

# Rank by absolute importance
coef_df <- coef_df[order(abs(coef_df$Weight), decreasing = TRUE), ]

head(coef_df)


```

```{r}
summary(coef_df$Weight)
```
